services:
  postgres:
    image: postgres:16
    container_name: adk_postgres
    environment:
      POSTGRES_DB: adk_sessions
      POSTGRES_USER: adk_user
      POSTGRES_PASSWORD: adk_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adk_user -d adk_sessions"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adk_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: adk_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - adk_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  adk_network:
    driver: bridge
